"""One-off fix: obs_on_elmer_mesh.nc / obs_on_elmer_mesh_pv.nc (ISMIP obs
regridded onto the SmallEnsTrans mesh) had the `velocity` field frozen at a
single snapshot across all 16 time records -- every record was bit-for-bit
identical, even though the raw satellite source (AntarcticaObsISMIP7-v1.2.nc)
genuinely varies year to year (confirmed e.g. real Pine Island Glacier
acceleration ~184 -> 344 m/yr across the 16 epochs). `dhdt` in the same files
was NOT affected -- it already varied correctly.

Root cause: the two output files are stale, generated by an older version of
the interpolation loop in CompareModVsObs.ipynb (cell "COMP1c") before some
since-lost fix -- the CURRENT cell source already writes `ds_nc["velocity"][t, :]`
correctly (matches build_ocx_mesh_products.py's velocity loop, which produces
correct varying output for the OCX mesh). So this script does not change any
interpolation logic; it just regenerates the `velocity` field with the same
scipy RegularGridInterpolator recipe already proven in
build_ocx_mesh_products.py, and patches it into the existing files in place
(dhdt/surface_bedmachine/node_basin are untouched -- already correct).

Run from postpro/jupyter/ in the postpro_ocx conda env. Derives node_xy for
the SmallEnsTrans mesh itself (same mesh-reference file / reprojection the
notebook's §0.4 uses), so no Jupyter kernel needs to be open.
"""
import time
from pathlib import Path

import netCDF4 as nc4
import numpy as np
import xarray as xr
import xugrid as xu
from scipy.interpolate import RegularGridInterpolator

JUP = Path(__file__).resolve().parent
OBS_FILE = JUP.parent / "DATA" / "AntarcticaObsISMIP7-v1.2.nc"
MESH_REF_FILE = JUP.parent.parent / "SmallEnsTrans" / "RUN3" / "TRANSIENT38nemofmpbuddcstc" / "restart_aa_trans_41.nc"
TARGETS = [JUP / "obs_on_elmer_mesh.nc", JUP / "obs_on_elmer_mesh_pv.nc"]

t0 = time.time()
def log(msg):
    print(f"[{time.time()-t0:7.1f}s] {msg}", flush=True)

log("Building node_xy for the SmallEnsTrans mesh (reproject lon/lat -> EPSG:3031) ...")
uds_ref = xu.open_dataset(str(MESH_REF_FILE), mask_and_scale=True, decode_times=True)
uds_ref.ugrid.set_crs("EPSG:4326")
uds_ref = uds_ref.ugrid.to_crs("EPSG:3031")
node_x = uds_ref["x"].values
node_y = uds_ref["y"].values
if node_x.ndim > 1 or "time" in uds_ref["x"].dims:
    node_x = uds_ref["x"].isel(time=0).values
    node_y = uds_ref["y"].isel(time=0).values
node_x = node_x.astype(np.float32)
node_y = node_y.astype(np.float32)
n_node = len(node_x)
log(f"n_node={n_node}")

log("Opening ISMIP obs (decode_times=True -- required, see time-epoch bug note below) ...")
# NB a SEPARATE bug (fixed 2026-07-10) affects the OCX-mesh obs time coordinate:
# opening this file with decode_times=False and then casting the raw integers
# straight to datetime64[D] silently reinterprets them against numpy's 1970
# epoch instead of the file's real "days since 1900-1-1" units -- shifts every
# timestamp ~70 years late. Not relevant to this script (only writes velocity
# DATA, not any time coordinate) but keep decode_times=True in any code that
# also touches vel_time/dhdt_time.
ISMIPobs = xr.open_dataset(str(OBS_FILE), decode_times=True)

x_min, x_max = node_x.min(), node_x.max()
y_min, y_max = node_y.min(), node_y.max()
pad = 50_000

def clip_obs_grid(obs_x, obs_y):
    xi = np.where((obs_x >= x_min - pad) & (obs_x <= x_max + pad))[0]
    yi = np.where((obs_y >= y_min - pad) & (obs_y <= y_max + pad))[0]
    return slice(xi[0], xi[-1] + 1), slice(yi[0], yi[-1] + 1)

obs_x_vel = ISMIPobs.vx_timeseries.x.values.astype(float)
obs_y_vel = ISMIPobs.vx_timeseries.y.values.astype(float)
xi_vel, yi_vel = clip_obs_grid(obs_x_vel, obs_y_vel)
x_vel_clip, y_vel_clip = obs_x_vel[xi_vel], obs_y_vel[yi_vel]
log("clip done")

BATCH = 200_000

def make_rgi(data_2d, y_coords, x_coords):
    y = y_coords.copy(); d = data_2d.copy().astype(np.float64)
    if y[0] > y[-1]:
        y = y[::-1]; d = d[::-1, :]
    d_filled = np.where(np.isfinite(d), d, 0.0)
    nan_mask = ~np.isfinite(d)
    rgi = RegularGridInterpolator((y, x_coords), d_filled, method="linear",
                                   bounds_error=False, fill_value=np.nan)
    rgi_nan = RegularGridInterpolator((y, x_coords), nan_mask.astype(float), method="linear",
                                       bounds_error=False, fill_value=1.0)
    return rgi, rgi_nan

def interp_to_nodes(rgi, rgi_nan, threshold=0.5):
    out = np.full(n_node, np.nan, dtype=np.float32)
    for start in range(0, n_node, BATCH):
        end = min(start + BATCH, n_node)
        pts = np.column_stack([node_y[start:end], node_x[start:end]])
        vals = rgi(pts).astype(np.float32)
        nan_frac = rgi_nan(pts)
        vals[nan_frac > threshold] = np.nan
        out[start:end] = vals
    return out

n_vel = ISMIPobs.vx_timeseries.sizes["vel_time"]
velocity_out = np.full((n_vel, n_node), np.nan, dtype=np.float32)
for t in range(n_vel):
    tt0 = time.time()
    vx_t = ISMIPobs.vx_timeseries.isel(vel_time=t).values[yi_vel, :][:, xi_vel]
    vy_t = ISMIPobs.vy_timeseries.isel(vel_time=t).values[yi_vel, :][:, xi_vel]
    spd = np.sqrt(vx_t**2 + vy_t**2).astype(np.float32)
    rgi, rgi_nan = make_rgi(spd, y_vel_clip, x_vel_clip)
    velocity_out[t, :] = interp_to_nodes(rgi, rgi_nan)
    log(f"  t={t}: mean={np.nanmean(velocity_out[t]):.2f}  [{time.time()-tt0:.1f}s]")

for f in TARGETS:
    d = nc4.Dataset(str(f), "a")
    assert d["velocity"].shape == velocity_out.shape, (f, d["velocity"].shape, velocity_out.shape)
    d["velocity"][:, :] = velocity_out
    d.close()
    log(f"patched {f.name}")

log("DONE")
